name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  TF_VERSION: "1.7.5"
  TF_IN_AUTOMATION: true

jobs:
  show-bash-settings:
    name: Show Bash Settings
    runs-on: ubuntu-latest
    steps:
      - name: Show ENV 
        run: env

      - name: Show options
        run: echo "$-"

      -name: Show files
       run: ls -lR

  init-validate:
    name: Init-Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init and validate
        run: |
            terraform -chdir=terraform init -backend=false
            make validate
