on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      aws-web-role-arn:
        required: true
        type: string
      aws-region:
        required: false
        type: string
      tf-version:
        required: false
        type: string

env:
  AWS_DEFAULT_REGION: ${{ inputs.aws-region || 'us-east-1' }}
  TF_VERSION: ${{ inputs.tf-version || '1.14.8' }}
  TF_IN_AUTOMATION: true

jobs:
  run-change:
    name: Run Change
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ inputs.aws-web-role-arn }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Package Lambba
        run: make package

      - name: TF Init and Validate
        run: |
          make init
          make validate

      - name: TF Plan
        run: make plan
        timeout-minutes: 2
        # Set debug messages to INFO
        # env:
        #  TF_LOG: INFO
