on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      aws-web-role-arn:
        required: false
        type: string
      aws-region:
        required: true
        type: string

env:
  AWS_DEFAULT_REGION: ${{ inputs.aws-region || 'us-east-1' }}

jobs:
  setup:
    name: Setup
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        
